import { RequestCategory, RequestStatus, ResponsibilityType, Priority, JobType } from '../types';

export interface MaintenanceRequestItem {
  id: string;
  requestNumber: string;
  createdAt: string;
  projectId: string;
  projectName: string;
  unitNumber: string;
  building: string;
  category: RequestCategory;
  jobType: JobType;
  description: string;
  responsibilityType: ResponsibilityType;
  assignee: string;
  vendorName?: string;
  status: RequestStatus;
  priority: Priority;
  targetDueDate: string;
  completedAt?: string;
  daysOpen: number;
  resolutionDays?: number;
}

export interface RequestsFilterState {
  projectId: string;
  category: RequestCategory | 'all';
  jobType: JobType | 'all';
  status: RequestStatus | 'all';
  responsibilityType: ResponsibilityType | 'all';
  priority: Priority | 'all';
  search: string;
  dateFrom: string;
  dateTo: string;
  overdue?: boolean;
}

export interface RequestsData {
  items: MaintenanceRequestItem[];
  summary: {
    total: number;
    open: number;
    inProgress: number;
    completed: number;
    overdue: number;
  };
}

export async function fetchMaintenanceRequests(
  _filters: RequestsFilterState
): Promise<RequestsData> {
  // Simulate API call
  await new Promise((resolve) => setTimeout(resolve, 500));

  const mockItems: MaintenanceRequestItem[] = [
    {
      id: 'REQ001',
      requestNumber: 'MR-2024-0001',
      createdAt: '2024-01-15 09:30',
      projectId: 'P001',
      projectName: 'SENA Park Grand รามอินทรา',
      unitNumber: 'A-101',
      building: 'Building A',
      category: 'electrical',
      jobType: 'repair',
      description: 'ไฟฟ้าดับบริเวณทางเดินชั้น 1',
      responsibilityType: 'JURISTIC_TECHNICIAN',
      assignee: 'สมชาย ช่างไฟ',
      status: 'in_progress',
      priority: 'high',
      targetDueDate: '2024-01-18',
      daysOpen: 5,
    },
    {
      id: 'REQ002',
      requestNumber: 'MR-2024-0002',
      createdAt: '2024-01-14 14:20',
      projectId: 'P001',
      projectName: 'SENA Park Grand รามอินทรา',
      unitNumber: 'B-205',
      building: 'Building B',
      category: 'plumbing',
      jobType: 'repair',
      description: 'ท่อน้ำรั่วในห้องน้ำส่วนกลาง',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท ประปาดี จำกัด',
      vendorName: 'บริษัท ประปาดี จำกัด',
      status: 'open',
      priority: 'urgent',
      targetDueDate: '2024-01-15',
      daysOpen: 6,
    },
    {
      id: 'REQ003',
      requestNumber: 'MR-2024-0003',
      createdAt: '2024-01-13 10:00',
      projectId: 'P002',
      projectName: 'SENA Villa ลาดพร้าว',
      unitNumber: 'C-301',
      building: 'Building C',
      category: 'aircon',
      jobType: 'repair',
      description: 'แอร์ไม่เย็น บริเวณล็อบบี้',
      responsibilityType: 'SENA_WARRANTY',
      assignee: 'SENA Service Center',
      status: 'pending_parts',
      priority: 'medium',
      targetDueDate: '2024-01-20',
      daysOpen: 7,
    },
    {
      id: 'REQ004',
      requestNumber: 'MR-2024-0004',
      createdAt: '2024-01-12 16:45',
      projectId: 'P002',
      projectName: 'SENA Villa ลาดพร้าว',
      unitNumber: 'A-102',
      building: 'Building A',
      category: 'elevator',
      jobType: 'repair',
      description: 'ลิฟต์มีเสียงดังผิดปกติ',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท ลิฟต์ไทย จำกัด',
      vendorName: 'บริษัท ลิฟต์ไทย จำกัด',
      status: 'completed',
      priority: 'high',
      targetDueDate: '2024-01-15',
      completedAt: '2024-01-14 11:30',
      daysOpen: 0,
      resolutionDays: 2,
    },
    {
      id: 'REQ005',
      requestNumber: 'MR-2024-0005',
      createdAt: '2024-01-11 08:15',
      projectId: 'P003',
      projectName: 'SENA Kith บางนา',
      unitNumber: 'D-501',
      building: 'Building D',
      category: 'common_area',
      jobType: 'complaint',
      description: 'ร้องเรียนเรื่องความสะอาดบริเวณสระว่ายน้ำ',
      responsibilityType: 'JURISTIC_TECHNICIAN',
      assignee: 'ทีมดูแลพื้นที่ส่วนกลาง',
      status: 'in_progress',
      priority: 'medium',
      targetDueDate: '2024-01-18',
      daysOpen: 9,
    },
    {
      id: 'REQ006',
      requestNumber: 'MR-2024-0006',
      createdAt: '2024-01-10 11:30',
      projectId: 'P003',
      projectName: 'SENA Kith บางนา',
      unitNumber: 'E-201',
      building: 'Building E',
      category: 'security',
      jobType: 'repair',
      description: 'กล้องวงจรปิดไม่ทำงาน บริเวณลานจอดรถ',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท ซีเคียวริตี้โปร จำกัด',
      vendorName: 'บริษัท ซีเคียวริตี้โปร จำกัด',
      status: 'open',
      priority: 'high',
      targetDueDate: '2024-01-13',
      daysOpen: 10,
    },
    {
      id: 'REQ007',
      requestNumber: 'MR-2024-0007',
      createdAt: '2024-01-09 09:00',
      projectId: 'P004',
      projectName: 'SENA Park รังสิต',
      unitNumber: 'F-102',
      building: 'Building F',
      category: 'structure',
      jobType: 'inspection',
      description: 'ตรวจสอบรอยร้าวผนังภายนอก',
      responsibilityType: 'SENA_WARRANTY',
      assignee: 'SENA Engineering',
      status: 'pending_approval',
      priority: 'medium',
      targetDueDate: '2024-01-16',
      daysOpen: 11,
    },
    {
      id: 'REQ008',
      requestNumber: 'MR-2024-0008',
      createdAt: '2024-01-08 14:00',
      projectId: 'P004',
      projectName: 'SENA Park รังสิต',
      unitNumber: 'G-301',
      building: 'Building G',
      category: 'fire_system',
      jobType: 'preventive',
      description: 'บำรุงรักษาระบบดับเพลิงประจำเดือน',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท ไฟร์เซฟ จำกัด',
      vendorName: 'บริษัท ไฟร์เซฟ จำกัด',
      status: 'completed',
      priority: 'low',
      targetDueDate: '2024-01-15',
      completedAt: '2024-01-12 16:00',
      daysOpen: 0,
      resolutionDays: 4,
    },
    {
      id: 'REQ009',
      requestNumber: 'MR-2024-0009',
      createdAt: '2024-01-07 10:45',
      projectId: 'P005',
      projectName: 'SENA Grand Home พระราม 2',
      unitNumber: 'H-401',
      building: 'Building H',
      category: 'landscape',
      jobType: 'repair',
      description: 'ต้นไม้ล้มขวางทางเดิน',
      responsibilityType: 'JURISTIC_TECHNICIAN',
      assignee: 'ทีมดูแลภูมิทัศน์',
      status: 'completed',
      priority: 'urgent',
      targetDueDate: '2024-01-07',
      completedAt: '2024-01-07 15:30',
      daysOpen: 0,
      resolutionDays: 1,
    },
    {
      id: 'REQ010',
      requestNumber: 'MR-2024-0010',
      createdAt: '2024-01-06 13:20',
      projectId: 'P005',
      projectName: 'SENA Grand Home พระราม 2',
      unitNumber: 'I-102',
      building: 'Building I',
      category: 'it_comm',
      jobType: 'repair',
      description: 'อินเตอร์เน็ตส่วนกลางใช้งานไม่ได้',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท ไอทีโซลูชั่น จำกัด',
      vendorName: 'บริษัท ไอทีโซลูชั่น จำกัด',
      status: 'in_progress',
      priority: 'high',
      targetDueDate: '2024-01-09',
      daysOpen: 14,
    },
    {
      id: 'REQ011',
      requestNumber: 'MR-2024-0011',
      createdAt: '2024-01-05 09:30',
      projectId: 'P006',
      projectName: 'SENA Park Ville บางใหญ่',
      unitNumber: 'J-201',
      building: 'Building J',
      category: 'sanitation',
      jobType: 'complaint',
      description: 'กลิ่นเหม็นจากท่อระบายน้ำ',
      responsibilityType: 'JURISTIC_TECHNICIAN',
      assignee: 'ทีมดูแลสุขาภิบาล',
      status: 'open',
      priority: 'medium',
      targetDueDate: '2024-01-12',
      daysOpen: 15,
    },
    {
      id: 'REQ012',
      requestNumber: 'MR-2024-0012',
      createdAt: '2024-01-04 11:00',
      projectId: 'P006',
      projectName: 'SENA Park Ville บางใหญ่',
      unitNumber: 'K-301',
      building: 'Building K',
      category: 'general_complaint',
      jobType: 'complaint',
      description: 'ร้องเรียนเรื่องเสียงดังจากห้องออกกำลังกาย',
      responsibilityType: 'JURISTIC_TECHNICIAN',
      assignee: 'ผู้จัดการนิติบุคคล',
      status: 'in_progress',
      priority: 'low',
      targetDueDate: '2024-01-18',
      daysOpen: 16,
    },
    {
      id: 'REQ013',
      requestNumber: 'MR-2024-0013',
      createdAt: '2024-01-03 15:45',
      projectId: 'P007',
      projectName: 'SENA Kith ศรีนครินทร์',
      unitNumber: 'L-501',
      building: 'Building L',
      category: 'electrical',
      jobType: 'repair',
      description: 'สวิตช์ไฟเสีย บริเวณทางเข้าอาคาร',
      responsibilityType: 'JURISTIC_TECHNICIAN',
      assignee: 'สมศักดิ์ ช่างไฟ',
      status: 'open',
      priority: 'medium',
      targetDueDate: '2024-01-10',
      daysOpen: 17,
    },
    {
      id: 'REQ014',
      requestNumber: 'MR-2024-0014',
      createdAt: '2024-01-02 08:00',
      projectId: 'P007',
      projectName: 'SENA Kith ศรีนครินทร์',
      unitNumber: 'M-102',
      building: 'Building M',
      category: 'plumbing',
      jobType: 'repair',
      description: 'ก๊อกน้ำรั่ว บริเวณห้องน้ำชั้น 1',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท ประปาดี จำกัด',
      vendorName: 'บริษัท ประปาดี จำกัด',
      status: 'completed',
      priority: 'low',
      targetDueDate: '2024-01-16',
      completedAt: '2024-01-10 14:00',
      daysOpen: 0,
      resolutionDays: 8,
    },
    {
      id: 'REQ015',
      requestNumber: 'MR-2024-0015',
      createdAt: '2024-01-01 10:30',
      projectId: 'P001',
      projectName: 'SENA Park Grand รามอินทรา',
      unitNumber: 'N-201',
      building: 'Building N',
      category: 'architecture',
      jobType: 'inspection',
      description: 'ตรวจสอบสีทาผนังลอก',
      responsibilityType: 'SENA_WARRANTY',
      assignee: 'SENA Quality Team',
      status: 'pending_approval',
      priority: 'low',
      targetDueDate: '2024-01-15',
      daysOpen: 19,
    },
    {
      id: 'REQ016',
      requestNumber: 'MR-2024-0016',
      createdAt: '2023-12-28 14:15',
      projectId: 'P002',
      projectName: 'SENA Villa ลาดพร้าว',
      unitNumber: 'O-301',
      building: 'Building O',
      category: 'aircon',
      jobType: 'preventive',
      description: 'ล้างแอร์ส่วนกลางประจำไตรมาส',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท แอร์คูล จำกัด',
      vendorName: 'บริษัท แอร์คูล จำกัด',
      status: 'completed',
      priority: 'low',
      targetDueDate: '2024-01-05',
      completedAt: '2024-01-03 11:00',
      daysOpen: 0,
      resolutionDays: 6,
    },
    {
      id: 'REQ017',
      requestNumber: 'MR-2024-0017',
      createdAt: '2023-12-25 09:00',
      projectId: 'P003',
      projectName: 'SENA Kith บางนา',
      unitNumber: 'P-401',
      building: 'Building P',
      category: 'elevator',
      jobType: 'inspection',
      description: 'ตรวจสอบระบบลิฟต์ประจำปี',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท ลิฟต์ไทย จำกัด',
      vendorName: 'บริษัท ลิฟต์ไทย จำกัด',
      status: 'completed',
      priority: 'medium',
      targetDueDate: '2024-01-10',
      completedAt: '2024-01-08 16:30',
      daysOpen: 0,
      resolutionDays: 14,
    },
    {
      id: 'REQ018',
      requestNumber: 'MR-2024-0018',
      createdAt: '2023-12-20 11:30',
      projectId: 'P004',
      projectName: 'SENA Park รังสิต',
      unitNumber: 'Q-102',
      building: 'Building Q',
      category: 'security',
      jobType: 'repair',
      description: 'ประตูรั้วอัตโนมัติไม่ทำงาน',
      responsibilityType: 'OUTSOURCE',
      assignee: 'บริษัท เกทเทค จำกัด',
      vendorName: 'บริษัท เกทเทค จำกัด',
      status: 'in_progress',
      priority: 'high',
      targetDueDate: '2023-12-27',
      daysOpen: 26,
    },
    {
      id: 'REQ019',
      requestNumber: 'MR-2024-0019',
      createdAt: '2023-12-15 08:45',
      projectId: 'P005',
      projectName: 'SENA Grand Home พระราม 2',
      unitNumber: 'R-201',
      building: 'Building R',
      category: 'structure',
      jobType: 'repair',
      description: 'ซ่อมแซมพื้นทางเดินแตก',
      responsibilityType: 'SENA_WARRANTY',
      assignee: 'SENA Construction',
      status: 'pending_parts',
      priority: 'medium',
      targetDueDate: '2024-01-05',
      daysOpen: 31,
    },
    {
      id: 'REQ020',
      requestNumber: 'MR-2024-0020',
      createdAt: '2023-12-10 13:00',
      projectId: 'P006',
      projectName: 'SENA Park Ville บางใหญ่',
      unitNumber: 'S-301',
      building: 'Building S',
      category: 'common_area',
      jobType: 'repair',
      description: 'ม้านั่งสวนสาธารณะพัง',
      responsibilityType: 'JURISTIC_TECHNICIAN',
      assignee: 'ทีมซ่อมบำรุง',
      status: 'open',
      priority: 'low',
      targetDueDate: '2023-12-24',
      daysOpen: 36,
    },
  ];

  return {
    items: mockItems,
    summary: {
      total: mockItems.length,
      open: mockItems.filter((i) => i.status === 'open').length,
      inProgress: mockItems.filter((i) => i.status === 'in_progress').length,
      completed: mockItems.filter((i) => i.status === 'completed').length,
      overdue: mockItems.filter((i) => i.daysOpen > 14 && i.status !== 'completed').length,
    },
  };
}
